repos:
  - repo: local
    hooks:
      - id: code-quality-simple
        name: Code Quality & Tests (Non-blocking)
        entry: bash scripts/pre-commit-hook.sh
        language: system
        always_run: true
        pass_filenames: false
        stages: [pre-commit]
        verbose: true
