[project]
name = "lexicon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "curl-cffi>=0.13.0",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "scrapy>=2.13.3",
    "seaborn>=0.13.2",
]
